/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getCompoId <em>Compo Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getCompoIda <em>Compo Ida</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdf <em>Compo Idf</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdt <em>Compo Idt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Component#getVars <em>Vars</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Compo Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compo Id</em>' attribute.
   * @see #setCompoId(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_CompoId()
   * @model
   * @generated
   */
  String getCompoId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Component#getCompoId <em>Compo Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compo Id</em>' attribute.
   * @see #getCompoId()
   * @generated
   */
  void setCompoId(String value);

  /**
   * Returns the value of the '<em><b>Compo Ida</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compo Ida</em>' attribute.
   * @see #setCompoIda(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_CompoIda()
   * @model
   * @generated
   */
  String getCompoIda();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIda <em>Compo Ida</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compo Ida</em>' attribute.
   * @see #getCompoIda()
   * @generated
   */
  void setCompoIda(String value);

  /**
   * Returns the value of the '<em><b>Compo Idf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compo Idf</em>' attribute.
   * @see #setCompoIdf(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_CompoIdf()
   * @model
   * @generated
   */
  String getCompoIdf();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdf <em>Compo Idf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compo Idf</em>' attribute.
   * @see #getCompoIdf()
   * @generated
   */
  void setCompoIdf(String value);

  /**
   * Returns the value of the '<em><b>Compo Idt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compo Idt</em>' attribute.
   * @see #setCompoIdt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_CompoIdt()
   * @model
   * @generated
   */
  String getCompoIdt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdt <em>Compo Idt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compo Idt</em>' attribute.
   * @see #getCompoIdt()
   * @generated
   */
  void setCompoIdt(String value);

  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getComponent_Vars()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVars();

} // Component
