/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getCoucheName <em>Couche Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer()
 * @model
 * @generated
 */
public interface Layer extends EObject
{
  /**
   * Returns the value of the '<em><b>Couche Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Couche Name</em>' attribute.
   * @see #setCoucheName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_CoucheName()
   * @model
   * @generated
   */
  String getCoucheName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getCoucheName <em>Couche Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Couche Name</em>' attribute.
   * @see #getCoucheName()
   * @generated
   */
  void setCoucheName(String value);

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_Components()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponents();

} // Layer
