/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExportModelImpl <em>Export Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExportModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExportModel()
   * @generated
   */
  int EXPORT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Export</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_MODEL__EXPORT = 0;

  /**
   * The number of structural features of the '<em>Export Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NetlistTypeImpl <em>Netlist Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NetlistTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNetlistType()
   * @generated
   */
  int NETLIST_TYPE = 1;

  /**
   * The feature id for the '<em><b>Docname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETLIST_TYPE__DOCNAME = 0;

  /**
   * The feature id for the '<em><b>Doctype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETLIST_TYPE__DOCTYPE = 1;

  /**
   * The feature id for the '<em><b>Layer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETLIST_TYPE__LAYER = 2;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETLIST_TYPE__NODES = 3;

  /**
   * The number of structural features of the '<em>Netlist Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETLIST_TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LayerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 2;

  /**
   * The feature id for the '<em><b>Couche Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__COUCHE_NAME = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComponentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 3;

  /**
   * The feature id for the '<em><b>Compo Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPO_ID = 0;

  /**
   * The feature id for the '<em><b>Compo Ida</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPO_IDA = 1;

  /**
   * The feature id for the '<em><b>Compo Idf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPO_IDF = 2;

  /**
   * The feature id for the '<em><b>Compo Idt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPO_IDT = 3;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__VARS = 4;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 4;

  /**
   * The feature id for the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VAR_NAME = 0;

  /**
   * The feature id for the '<em><b>Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__TAGS = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TagImpl <em>Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TagImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTag()
   * @generated
   */
  int TAG = 5;

  /**
   * The feature id for the '<em><b>Tag Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__TAG_NUM = 0;

  /**
   * The feature id for the '<em><b>Tag Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__TAG_NAME = 1;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG__VAR = 2;

  /**
   * The number of structural features of the '<em>Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodesImpl <em>Nodes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodesImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodes()
   * @generated
   */
  int NODES = 6;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODES__NODES = 0;

  /**
   * The number of structural features of the '<em>Nodes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NodeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNode()
   * @generated
   */
  int NODE = 7;

  /**
   * The feature id for the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE_NAME = 0;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__LINKS = 1;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
   * @generated
   */
  int LINK = 8;

  /**
   * The feature id for the '<em><b>Comp ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__COMP_ID = 0;

  /**
   * The feature id for the '<em><b>Port ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__PORT_ID = 1;

  /**
   * The feature id for the '<em><b>Port Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__PORT_NAME = 2;

  /**
   * The feature id for the '<em><b>Port Name2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__PORT_NAME2 = 3;

  /**
   * The feature id for the '<em><b>Balise Fermante</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__BALISE_FERMANTE = 4;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ExportModel <em>Export Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Export Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExportModel
   * @generated
   */
  EClass getExportModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExportModel#getExport <em>Export</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Export</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExportModel#getExport()
   * @see #getExportModel()
   * @generated
   */
  EReference getExportModel_Export();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.NetlistType <em>Netlist Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Netlist Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.NetlistType
   * @generated
   */
  EClass getNetlistType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NetlistType#getDocname <em>Docname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Docname</em>'.
   * @see org.xtext.example.mydsl.myDsl.NetlistType#getDocname()
   * @see #getNetlistType()
   * @generated
   */
  EAttribute getNetlistType_Docname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.NetlistType#getDoctype <em>Doctype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Doctype</em>'.
   * @see org.xtext.example.mydsl.myDsl.NetlistType#getDoctype()
   * @see #getNetlistType()
   * @generated
   */
  EAttribute getNetlistType_Doctype();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.NetlistType#getLayer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layer</em>'.
   * @see org.xtext.example.mydsl.myDsl.NetlistType#getLayer()
   * @see #getNetlistType()
   * @generated
   */
  EReference getNetlistType_Layer();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.NetlistType#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.NetlistType#getNodes()
   * @see #getNetlistType()
   * @generated
   */
  EReference getNetlistType_Nodes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Layer#getCoucheName <em>Couche Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Couche Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Layer#getCoucheName()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_CoucheName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Layer#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.xtext.example.mydsl.myDsl.Layer#getComponents()
   * @see #getLayer()
   * @generated
   */
  EReference getLayer_Components();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Component#getCompoId <em>Compo Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compo Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getCompoId()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_CompoId();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIda <em>Compo Ida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compo Ida</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getCompoIda()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_CompoIda();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdf <em>Compo Idf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compo Idf</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getCompoIdf()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_CompoIdf();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Component#getCompoIdt <em>Compo Idt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compo Idt</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getCompoIdt()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_CompoIdt();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Component#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getVars()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Vars();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Variable#getVarName <em>Var Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable#getVarName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_VarName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Variable#getTags <em>Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tags</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable#getTags()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_Tags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Tag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tag</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag
   * @generated
   */
  EClass getTag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Tag#getTagNum <em>Tag Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag Num</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag#getTagNum()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_TagNum();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Tag#getTagName <em>Tag Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag#getTagName()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_TagName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Tag#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.example.mydsl.myDsl.Tag#getVar()
   * @see #getTag()
   * @generated
   */
  EAttribute getTag_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nodes
   * @generated
   */
  EClass getNodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Nodes#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nodes#getNodes()
   * @see #getNodes()
   * @generated
   */
  EReference getNodes_Nodes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Node#getNodeName <em>Node Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getNodeName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_NodeName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Node#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Links</em>'.
   * @see org.xtext.example.mydsl.myDsl.Node#getLinks()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Links();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getCompID <em>Comp ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comp ID</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getCompID()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_CompID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getPortID <em>Port ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port ID</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getPortID()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_PortID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getPortName <em>Port Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getPortName()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_PortName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getPortName2 <em>Port Name2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port Name2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getPortName2()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_PortName2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Link#getBaliseFermante <em>Balise Fermante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Balise Fermante</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getBaliseFermante()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_BaliseFermante();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExportModelImpl <em>Export Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExportModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExportModel()
     * @generated
     */
    EClass EXPORT_MODEL = eINSTANCE.getExportModel();

    /**
     * The meta object literal for the '<em><b>Export</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPORT_MODEL__EXPORT = eINSTANCE.getExportModel_Export();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NetlistTypeImpl <em>Netlist Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NetlistTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNetlistType()
     * @generated
     */
    EClass NETLIST_TYPE = eINSTANCE.getNetlistType();

    /**
     * The meta object literal for the '<em><b>Docname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NETLIST_TYPE__DOCNAME = eINSTANCE.getNetlistType_Docname();

    /**
     * The meta object literal for the '<em><b>Doctype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NETLIST_TYPE__DOCTYPE = eINSTANCE.getNetlistType_Doctype();

    /**
     * The meta object literal for the '<em><b>Layer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETLIST_TYPE__LAYER = eINSTANCE.getNetlistType_Layer();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETLIST_TYPE__NODES = eINSTANCE.getNetlistType_Nodes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LayerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Couche Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__COUCHE_NAME = eINSTANCE.getLayer_CoucheName();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYER__COMPONENTS = eINSTANCE.getLayer_Components();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComponentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Compo Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__COMPO_ID = eINSTANCE.getComponent_CompoId();

    /**
     * The meta object literal for the '<em><b>Compo Ida</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__COMPO_IDA = eINSTANCE.getComponent_CompoIda();

    /**
     * The meta object literal for the '<em><b>Compo Idf</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__COMPO_IDF = eINSTANCE.getComponent_CompoIdf();

    /**
     * The meta object literal for the '<em><b>Compo Idt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__COMPO_IDT = eINSTANCE.getComponent_CompoIdt();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__VARS = eINSTANCE.getComponent_Vars();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Var Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VAR_NAME = eINSTANCE.getVariable_VarName();

    /**
     * The meta object literal for the '<em><b>Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__TAGS = eINSTANCE.getVariable_Tags();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TagImpl <em>Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TagImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTag()
     * @generated
     */
    EClass TAG = eINSTANCE.getTag();

    /**
     * The meta object literal for the '<em><b>Tag Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__TAG_NUM = eINSTANCE.getTag_TagNum();

    /**
     * The meta object literal for the '<em><b>Tag Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__TAG_NAME = eINSTANCE.getTag_TagName();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG__VAR = eINSTANCE.getTag_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodesImpl <em>Nodes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodesImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNodes()
     * @generated
     */
    EClass NODES = eINSTANCE.getNodes();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODES__NODES = eINSTANCE.getNodes_Nodes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NodeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Node Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NODE_NAME = eINSTANCE.getNode_NodeName();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__LINKS = eINSTANCE.getNode_Links();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Comp ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__COMP_ID = eINSTANCE.getLink_CompID();

    /**
     * The meta object literal for the '<em><b>Port ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__PORT_ID = eINSTANCE.getLink_PortID();

    /**
     * The meta object literal for the '<em><b>Port Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__PORT_NAME = eINSTANCE.getLink_PortName();

    /**
     * The meta object literal for the '<em><b>Port Name2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__PORT_NAME2 = eINSTANCE.getLink_PortName2();

    /**
     * The meta object literal for the '<em><b>Balise Fermante</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__BALISE_FERMANTE = eINSTANCE.getLink_BaliseFermante();

  }

} //MyDslPackage
