/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Netlist Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NetlistType#getDocname <em>Docname</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NetlistType#getDoctype <em>Doctype</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NetlistType#getLayer <em>Layer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NetlistType#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNetlistType()
 * @model
 * @generated
 */
public interface NetlistType extends EObject
{
  /**
   * Returns the value of the '<em><b>Docname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Docname</em>' attribute.
   * @see #setDocname(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNetlistType_Docname()
   * @model
   * @generated
   */
  String getDocname();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NetlistType#getDocname <em>Docname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Docname</em>' attribute.
   * @see #getDocname()
   * @generated
   */
  void setDocname(String value);

  /**
   * Returns the value of the '<em><b>Doctype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doctype</em>' attribute.
   * @see #setDoctype(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNetlistType_Doctype()
   * @model
   * @generated
   */
  String getDoctype();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NetlistType#getDoctype <em>Doctype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doctype</em>' attribute.
   * @see #getDoctype()
   * @generated
   */
  void setDoctype(String value);

  /**
   * Returns the value of the '<em><b>Layer</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Layer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layer</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNetlistType_Layer()
   * @model containment="true"
   * @generated
   */
  EList<Layer> getLayer();

  /**
   * Returns the value of the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' containment reference.
   * @see #setNodes(Nodes)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNetlistType_Nodes()
   * @model containment="true"
   * @generated
   */
  Nodes getNodes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.NetlistType#getNodes <em>Nodes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodes</em>' containment reference.
   * @see #getNodes()
   * @generated
   */
  void setNodes(Nodes value);

} // NetlistType
