/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Tag#getTagNum <em>Tag Num</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Tag#getTagName <em>Tag Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Tag#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag()
 * @model
 * @generated
 */
public interface Tag extends EObject
{
  /**
   * Returns the value of the '<em><b>Tag Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag Num</em>' attribute.
   * @see #setTagNum(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag_TagNum()
   * @model
   * @generated
   */
  int getTagNum();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Tag#getTagNum <em>Tag Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag Num</em>' attribute.
   * @see #getTagNum()
   * @generated
   */
  void setTagNum(int value);

  /**
   * Returns the value of the '<em><b>Tag Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag Name</em>' attribute.
   * @see #setTagName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag_TagName()
   * @model
   * @generated
   */
  String getTagName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Tag#getTagName <em>Tag Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag Name</em>' attribute.
   * @see #getTagName()
   * @generated
   */
  void setTagName(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTag_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Tag#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

} // Tag
