/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Component;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl#getCompoId <em>Compo Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl#getCompoIda <em>Compo Ida</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl#getCompoIdf <em>Compo Idf</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl#getCompoIdt <em>Compo Idt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl#getVars <em>Vars</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComponentImpl extends MinimalEObjectImpl.Container implements Component
{
  /**
   * The default value of the '{@link #getCompoId() <em>Compo Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoId()
   * @generated
   * @ordered
   */
  protected static final String COMPO_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompoId() <em>Compo Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoId()
   * @generated
   * @ordered
   */
  protected String compoId = COMPO_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getCompoIda() <em>Compo Ida</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIda()
   * @generated
   * @ordered
   */
  protected static final String COMPO_IDA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompoIda() <em>Compo Ida</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIda()
   * @generated
   * @ordered
   */
  protected String compoIda = COMPO_IDA_EDEFAULT;

  /**
   * The default value of the '{@link #getCompoIdf() <em>Compo Idf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIdf()
   * @generated
   * @ordered
   */
  protected static final String COMPO_IDF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompoIdf() <em>Compo Idf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIdf()
   * @generated
   * @ordered
   */
  protected String compoIdf = COMPO_IDF_EDEFAULT;

  /**
   * The default value of the '{@link #getCompoIdt() <em>Compo Idt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIdt()
   * @generated
   * @ordered
   */
  protected static final String COMPO_IDT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompoIdt() <em>Compo Idt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompoIdt()
   * @generated
   * @ordered
   */
  protected String compoIdt = COMPO_IDT_EDEFAULT;

  /**
   * The cached value of the '{@link #getVars() <em>Vars</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVars()
   * @generated
   * @ordered
   */
  protected EList<Variable> vars;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.COMPONENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCompoId()
  {
    return compoId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCompoId(String newCompoId)
  {
    String oldCompoId = compoId;
    compoId = newCompoId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPONENT__COMPO_ID, oldCompoId, compoId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCompoIda()
  {
    return compoIda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCompoIda(String newCompoIda)
  {
    String oldCompoIda = compoIda;
    compoIda = newCompoIda;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPONENT__COMPO_IDA, oldCompoIda, compoIda));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCompoIdf()
  {
    return compoIdf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCompoIdf(String newCompoIdf)
  {
    String oldCompoIdf = compoIdf;
    compoIdf = newCompoIdf;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPONENT__COMPO_IDF, oldCompoIdf, compoIdf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCompoIdt()
  {
    return compoIdt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCompoIdt(String newCompoIdt)
  {
    String oldCompoIdt = compoIdt;
    compoIdt = newCompoIdt;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPONENT__COMPO_IDT, oldCompoIdt, compoIdt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Variable> getVars()
  {
    if (vars == null)
    {
      vars = new EObjectContainmentEList<Variable>(Variable.class, this, MyDslPackage.COMPONENT__VARS);
    }
    return vars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPONENT__VARS:
        return ((InternalEList<?>)getVars()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPONENT__COMPO_ID:
        return getCompoId();
      case MyDslPackage.COMPONENT__COMPO_IDA:
        return getCompoIda();
      case MyDslPackage.COMPONENT__COMPO_IDF:
        return getCompoIdf();
      case MyDslPackage.COMPONENT__COMPO_IDT:
        return getCompoIdt();
      case MyDslPackage.COMPONENT__VARS:
        return getVars();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPONENT__COMPO_ID:
        setCompoId((String)newValue);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDA:
        setCompoIda((String)newValue);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDF:
        setCompoIdf((String)newValue);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDT:
        setCompoIdt((String)newValue);
        return;
      case MyDslPackage.COMPONENT__VARS:
        getVars().clear();
        getVars().addAll((Collection<? extends Variable>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPONENT__COMPO_ID:
        setCompoId(COMPO_ID_EDEFAULT);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDA:
        setCompoIda(COMPO_IDA_EDEFAULT);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDF:
        setCompoIdf(COMPO_IDF_EDEFAULT);
        return;
      case MyDslPackage.COMPONENT__COMPO_IDT:
        setCompoIdt(COMPO_IDT_EDEFAULT);
        return;
      case MyDslPackage.COMPONENT__VARS:
        getVars().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPONENT__COMPO_ID:
        return COMPO_ID_EDEFAULT == null ? compoId != null : !COMPO_ID_EDEFAULT.equals(compoId);
      case MyDslPackage.COMPONENT__COMPO_IDA:
        return COMPO_IDA_EDEFAULT == null ? compoIda != null : !COMPO_IDA_EDEFAULT.equals(compoIda);
      case MyDslPackage.COMPONENT__COMPO_IDF:
        return COMPO_IDF_EDEFAULT == null ? compoIdf != null : !COMPO_IDF_EDEFAULT.equals(compoIdf);
      case MyDslPackage.COMPONENT__COMPO_IDT:
        return COMPO_IDT_EDEFAULT == null ? compoIdt != null : !COMPO_IDT_EDEFAULT.equals(compoIdt);
      case MyDslPackage.COMPONENT__VARS:
        return vars != null && !vars.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (compoId: ");
    result.append(compoId);
    result.append(", compoIda: ");
    result.append(compoIda);
    result.append(", compoIdf: ");
    result.append(compoIdf);
    result.append(", compoIdt: ");
    result.append(compoIdt);
    result.append(')');
    return result.toString();
  }

} //ComponentImpl
