/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Link;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl#getCompID <em>Comp ID</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl#getPortID <em>Port ID</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl#getPortName <em>Port Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl#getPortName2 <em>Port Name2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl#getBaliseFermante <em>Balise Fermante</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LinkImpl extends MinimalEObjectImpl.Container implements Link
{
  /**
   * The default value of the '{@link #getCompID() <em>Comp ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompID()
   * @generated
   * @ordered
   */
  protected static final String COMP_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCompID() <em>Comp ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCompID()
   * @generated
   * @ordered
   */
  protected String compID = COMP_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getPortID() <em>Port ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortID()
   * @generated
   * @ordered
   */
  protected static final String PORT_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPortID() <em>Port ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortID()
   * @generated
   * @ordered
   */
  protected String portID = PORT_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getPortName() <em>Port Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortName()
   * @generated
   * @ordered
   */
  protected static final String PORT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPortName() <em>Port Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortName()
   * @generated
   * @ordered
   */
  protected String portName = PORT_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getPortName2() <em>Port Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortName2()
   * @generated
   * @ordered
   */
  protected static final String PORT_NAME2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPortName2() <em>Port Name2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPortName2()
   * @generated
   * @ordered
   */
  protected String portName2 = PORT_NAME2_EDEFAULT;

  /**
   * The default value of the '{@link #getBaliseFermante() <em>Balise Fermante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaliseFermante()
   * @generated
   * @ordered
   */
  protected static final String BALISE_FERMANTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBaliseFermante() <em>Balise Fermante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBaliseFermante()
   * @generated
   * @ordered
   */
  protected String baliseFermante = BALISE_FERMANTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LinkImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.LINK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCompID()
  {
    return compID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCompID(String newCompID)
  {
    String oldCompID = compID;
    compID = newCompID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LINK__COMP_ID, oldCompID, compID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPortID()
  {
    return portID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPortID(String newPortID)
  {
    String oldPortID = portID;
    portID = newPortID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LINK__PORT_ID, oldPortID, portID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPortName()
  {
    return portName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPortName(String newPortName)
  {
    String oldPortName = portName;
    portName = newPortName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LINK__PORT_NAME, oldPortName, portName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPortName2()
  {
    return portName2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPortName2(String newPortName2)
  {
    String oldPortName2 = portName2;
    portName2 = newPortName2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LINK__PORT_NAME2, oldPortName2, portName2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBaliseFermante()
  {
    return baliseFermante;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBaliseFermante(String newBaliseFermante)
  {
    String oldBaliseFermante = baliseFermante;
    baliseFermante = newBaliseFermante;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LINK__BALISE_FERMANTE, oldBaliseFermante, baliseFermante));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.LINK__COMP_ID:
        return getCompID();
      case MyDslPackage.LINK__PORT_ID:
        return getPortID();
      case MyDslPackage.LINK__PORT_NAME:
        return getPortName();
      case MyDslPackage.LINK__PORT_NAME2:
        return getPortName2();
      case MyDslPackage.LINK__BALISE_FERMANTE:
        return getBaliseFermante();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.LINK__COMP_ID:
        setCompID((String)newValue);
        return;
      case MyDslPackage.LINK__PORT_ID:
        setPortID((String)newValue);
        return;
      case MyDslPackage.LINK__PORT_NAME:
        setPortName((String)newValue);
        return;
      case MyDslPackage.LINK__PORT_NAME2:
        setPortName2((String)newValue);
        return;
      case MyDslPackage.LINK__BALISE_FERMANTE:
        setBaliseFermante((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LINK__COMP_ID:
        setCompID(COMP_ID_EDEFAULT);
        return;
      case MyDslPackage.LINK__PORT_ID:
        setPortID(PORT_ID_EDEFAULT);
        return;
      case MyDslPackage.LINK__PORT_NAME:
        setPortName(PORT_NAME_EDEFAULT);
        return;
      case MyDslPackage.LINK__PORT_NAME2:
        setPortName2(PORT_NAME2_EDEFAULT);
        return;
      case MyDslPackage.LINK__BALISE_FERMANTE:
        setBaliseFermante(BALISE_FERMANTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LINK__COMP_ID:
        return COMP_ID_EDEFAULT == null ? compID != null : !COMP_ID_EDEFAULT.equals(compID);
      case MyDslPackage.LINK__PORT_ID:
        return PORT_ID_EDEFAULT == null ? portID != null : !PORT_ID_EDEFAULT.equals(portID);
      case MyDslPackage.LINK__PORT_NAME:
        return PORT_NAME_EDEFAULT == null ? portName != null : !PORT_NAME_EDEFAULT.equals(portName);
      case MyDslPackage.LINK__PORT_NAME2:
        return PORT_NAME2_EDEFAULT == null ? portName2 != null : !PORT_NAME2_EDEFAULT.equals(portName2);
      case MyDslPackage.LINK__BALISE_FERMANTE:
        return BALISE_FERMANTE_EDEFAULT == null ? baliseFermante != null : !BALISE_FERMANTE_EDEFAULT.equals(baliseFermante);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (CompID: ");
    result.append(compID);
    result.append(", portID: ");
    result.append(portID);
    result.append(", portName: ");
    result.append(portName);
    result.append(", portName2: ");
    result.append(portName2);
    result.append(", baliseFermante: ");
    result.append(baliseFermante);
    result.append(')');
    return result.toString();
  }

} //LinkImpl
